id: P006840
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:26:00.374740
source_metadata:
  id: bdr:W29979
  title: སྙན་ངག
  author: ''
  volumes:
    b8045006e0d84cbd8c774a9f04e9ff34:
      image_group_id: I5719
      title: ''
      volume_number: 1
      total_pages: 585
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
