id: P006840
initial_creation_type: ocr
source_metadata:
  id: bdr:W29979
  title: སྙན་ངག
  author: ''
  volumes:
    b8045006e0d84cbd8c774a9f04e9ff34:
      image_group_id: I5719
      title: ''
      volume_number: 1
      total_pages: 585
